apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /var/log/nginx
      - name: log-agent
        image: busybox
        command: ["sh", "-c", "tail -f /var/log/nginx/access.log"]
        volumeMounts:
        - name: logs
          mountPath: /var/log/nginx
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "web"
        effect: "NoSchedule"
      volumes:
      - name: logs
        emptyDir: {}
